apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerfile
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /workspaces/cloudnative_learning/kaniko/volume # replace with local directory, such as "/home/<user-name>/kaniko"